name: Autojson 

on:
  workflow_dispatch: 
  push:
    branches:
      - Xiaomi.eu
  schedule:
    - cron: '0 * * * *' # Runs at the start of every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install apktool
        run: sudo apt-get install -y apktool
        
      - name: Grant execute permission for script
        run: chmod +x *.sh

      - name: Generate JSON file
        run: ./pif_old.sh -p

      - name: Check differences in chiteroman.json
        run: |
          if git diff --exit-code chiteroman.json; then
            echo "chiteroman.json is the same, no need to commit."
          else
            git config --global user.name "grass2"
            git config --global user.email "username@users.noreply.github.com"
            git add chiteroman.json
            git add osmosis.json
            git add device_osmosis.json
            git commit -m "Update pif.json"
            git push
          fi
